### ISSUE TITLE
Wave transition gap

### ISSUE THREAD

**Issue by pkrauss3** [app-generator/jinja-pixel-old#1]
https://github.com/app-generator/jinja-pixel-lite/blob/b519951c9f93a67205a09a94b2a54eebfd11d29f/app/templates/index.html#L31

The above piece of div results in a wave graphic. However if you zoom out to anything <=50% theres a gap between elements that results in a blue line from the main section.

**Comment by app-generator** [comment]
Hello,

Please provide more information:
- steps to reproduce the problem
- OS and browser version
- A screenshot that highlights the reported issue.

Thank you!
